.PHONY: build
build:
	docker-compose build
.PHONY: up
up:
	docker-compose up
.PHONY: upd
upd:
	docker-compose up -d
.PHONY: exec-s
exec-s:
	docker-compose exec php_sample /bin/bash
.PHONY: down
down:
	docker-compose down
